### ISSUE TITLE
New RegNNN and StrRegNNN PVs

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#110]
We recently have our new registers and string registers installed. The PV names are in the screenshot. There are 30 registers and 30 string registers for each hutch and we can add more if need be. As a result Suresh wants me to migrate the register info from the old VME ones to the new ones. 

I understand this is a lot of typing from your end, so if you could show me a template for the string registers and the registers with only a couple of fields defined, I can take care of the rest and merge into the main branch after successful testing. 

It's Ok that we don't decide on which StrReg contains what information for now since I'll be writing my own Nexus metadata file.

Thank you!

![image](https://github.com/user-attachments/assets/51035a42-20ea-4085-9c80-71723da0381a)
![image](https://github.com/user-attachments/assets/38e0b392-7286-4c99-b14b-b9bf237ba1cb)
![image](https://github.com/user-attachments/assets/092f5048-b27f-4b26-8601-f480e1aae0f7)

_Originally posted by @qzhang234 in https://github.com/aps-8id-dys/bluesky/issues/101#issuecomment-2489576579_

**Comment by qzhang234** [comment]
This issue can be addressed by simply changing the PV prefix when instantiating the class. I can mark it as solved.
