### ISSUE TITLE
add check for proper subnet

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#2]
Apparently, some workstations at 8-ID-I are not on the same subnet.  Check for the proper subnet as the instrument package is started or the EPICS controls will not work.

**Comment by sureshnaps** [comment]
Pete,

Quartz has been moved to BCDA subnet as it is being used for testing some apsu controls with your group. Snow is kind of dead, waiting on IT to revive.

Please use talc, pearl, agate, lapis (any of these).

Suresh


From: Pete R Jemian ***@***.***>
Date: Friday, December 16, 2022 at 2:17 PM
To: aps-8id-dys/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aps-8id-dys/bluesky] add check for proper subnet (Issue #2)

Apparently, some workstations at 8-ID-I are not on the same subnet. Check for the proper subnet as the instrument package is started or the EPICS controls will not work.

**Comment by prjemian** [comment]
For the March demo, we decided to run QS on lapis.  The starter script adds this check: https://github.com/aps-8id-dys/bluesky/blob/5ffd671ba775d0739df61961c012a14c84f8e51e/run_qs.sh#L22-L26
