### ISSUE TITLE
Bluesky plans for commissioning, week of 2024-06-18

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#30]
@sureshnaps asks (by email):

Could we set up scripts to do the following:

* [x] #31
* [x] #35
* [x] #32
* [x] #33
* [x] #34

These will be the first things needed from next week to commission the beamline.

**Comment by qzhang234** [comment]
We have successfully supported an external user group with 100% Bluesky in Oct 2024. This issue can be marked as solved.
