### ISSUE TITLE
create ophyd objects for certain beam line equipment

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#60]
Create support for the items marked by red boxes:
![image](https://github.com/user-attachments/assets/f670276c-5243-42c7-96f3-3a06f3b1ff88)

- [ ] #61
- [ ] #62
- [ ] #63
- [ ] #64

note: this screen created by `start_epics`

**Comment by prjemian** [comment]
The 8-ID-E and 8-ID-I stations are separate instruments.  Are we combining support for both in this one repository?

**Comment by prjemian** [comment]
If they will be operated at the same time, we should not combine their controls here.

**Comment by MDecarabas** [comment]
I think all of 8id can live in 1 package, and depending on which station it is being used on different devices can be imported

**Comment by prjemian** [comment]
Asked the beam line team if the two instruments are operated at the same time.  That's the important point to make the decision.

**Comment by sureshnaps** [comment]
the 2 instruments will not take beam at the same time but i can imagine operating the 2 instruments at the same time.
________________________________

**Comment by sureshnaps** [comment]
as long as I can run bluesky8IDI and bluesky8IDE concurrently and also 8IDI should not load all the 8IDE devices and vice versa unless needed by choice


From: Suresh N. ***@***.***>
Date: Tuesday, August 27, 2024 at 2:24 PM
To: aps-8id-dys/bluesky ***@***.***>
Cc: Narayanan, Suresh ***@***.***>, Your activity ***@***.***>
Subject: Re: [aps-8id-dys/bluesky] create ophyd objects for certain beam line equipment (Issue #60)
the 2 instruments will not take beam at the same time but i can imagine operating the 2 instruments at the same time. ________________________________ From: Pete R Jemian ***@ ***. ***> Sent: Tuesday, August 27, 2024 1: 49 PM To: aps-8id-dys/bluesky
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd
the 2 instruments will not take beam at the same time but i can imagine operating the 2 instruments at the same time.
________________________________

**Comment by prjemian** [comment]
Thanks.  That's a good requirement for us to meet.  @MDecarabas & I will work it out.

**Comment by prjemian** [comment]
Issues are created for all objects.  Planning for concurrent operations of E & I stations will continue is separate issue.
