### ISSUE TITLE
bp.rel_scan does not trigger eiger4M

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/bluesky#77]
**Describe the bug**
bp.rel_scan does not trigger eiger4M

**To Reproduce**
I changed `eiger4M.stats1.mean_value` to `hinted` and did:
```
RE(bp.rel_scan([eiger4M.stats1.mean_value],sample.x, -2, 2, 20))
```

**Expected behavior**
I expect the scan to trigger the detector at every step, and I'm able to view the spec file with pyMca.

**Screenshots**
![pymca](https://github.com/user-attachments/assets/0b12db0f-f09b-4d9b-bda2-db9f1d048c27)
![scan](https://github.com/user-attachments/assets/3ee2a026-56ee-40ec-a17f-4ab3897cabc3)

**Environment (please complete the following information):**
 - OS: Linux RHEL
 - Environment: bluesky_2024_3, Code: `/home/beams/8IDIUSER/bluesky/scripts`

**Additional context**
`bp.count` works and can trigger the detector
![count](https://github.com/user-attachments/assets/db84ad7b-8056-4005-b1f1-cbfd23198655)

**Comment by prjemian** [comment]
Can you repeat the same scan with this one (seemingly) minor change?
`RE(bp.rel_scan([eiger4M],sample.x, -2, 2, 20))`

### Explanation

Your previous command, `RE(bp.rel_scan([eiger4M.stats1.mean_value],sample.x, -2, 2, 20))` seemed like the right idea.  You asked for the signal you want to see.  But this signal does not know how to trigger its parent device.  So instead, you *configure* (as you have done) the signal to be reported.  Then you supply the entire detector to the `count` plan.  The detector knows how to trigger.

**Comment by prjemian** [comment]
That did it!
