### ISSUE TITLE
add flag motors

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#80]
- add them for flag1ad - flag3ad
- rename flag4ad motor to something else

Use some consistent names.  The motor called `flag4` is confusing

**Comment by prjemian** [comment]
`fl1` and `fl2`

**Comment by qzhang234** [comment]
This issue has been resolved as of 11/21/2024

![image](https://github.com/user-attachments/assets/8a10a466-d185-4d6c-b01d-90426cebed19)
